version: '3'

services:
  k3s-server:
    image: "rancher/k3s:v1.25.4-k3s1"
    command: server
    container_name: k3s-server
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      - K3S_TOKEN=${K3S_TOKEN:-unsecureToken1234}
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - k3s-server-vol:/var/lib/rancher/k3s
      # This is just so that we get the kubeconfig file out
      - .:/output
    ports:
      - 6443:6443  # Kubernetes API Server
      - 80:80      # Ingress controller port 80
      - 443:443    # Ingress controller port 443

  k3s-agent:
    image: "rancher/k3s:v1.25.4-k3s1"
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      - K3S_URL=https://k3s-server:6443
      - K3S_TOKEN=${K3S_TOKEN:-unsecureToken1234}

  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: registry.ryax.org/utils/slurm-bebida:22.12.0
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - "mysql"

  slurmctld:
    image: registry.ryax.org/utils/slurm-bebida:22.12.0
    privileged: True
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      # Give access to the k3s kubeconfig file
      - .:/usr/local/etc/bebida
    expose:
      - 6817
    ports:
      - "127.0.0.1:2222:22"
    depends_on:
      - "slurmdbd"
      # Wee need the kubeconfig file to be created at startup
      - "k3s-server"

  c1:
    image: registry.ryax.org/utils/slurm-bebida:22.12.0
    privileged: True
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    tmpfs:
      - /run
      - /var/run
      - /var/run/munge
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    restart: always
    environment:
      - K3S_URL=https://k3s-server:6443
      - K3S_TOKEN=${K3S_TOKEN:-unsecureToken1234}
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - k3s-c1-vol:/var/lib/rancher/k3s
      - k3s-c1-conf:/etc/rancher
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  c2:
    image: registry.ryax.org/utils/slurm-bebida:22.12.0
    privileged: True
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    tmpfs:
      - /run
      - /var/run
      - /var/run/munge
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    restart: always
    environment:
      - K3S_URL=https://k3s-server:6443
      - K3S_TOKEN=${K3S_TOKEN:-unsecureToken1234}
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - k3s-c2-vol:/var/lib/rancher/k3s
      - k3s-c2-conf:/etc/rancher
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

volumes:
  k3s-server-vol: {}
  k3s-c1-vol: {}
  k3s-c2-vol: {}
  k3s-c1-conf: {}
  k3s-c2-conf: {}
  etc_munge: {}
  etc_slurm: {}
  slurm_jobdir: {}
  var_lib_mysql: {}
  var_log_slurm: {}
